#! /usr/bin/env bash
#
#
BLUE="34"
YELLOW="33"
BOLDBLUE="\e[1;${BLUE}m"
BOLDYELLOW="\e[1;${YELLOW}m"
ENDCOLOR="\e[0m"
BINARY_SEARCH_JS=js/binary_search.js
BINARY_SEARCH_PY=python/binary_search.py
ARRAY_LENGTH=$1
ITEM_TO_FIND=$2

exec_binary_search_js() {
    if [[ -f "$BINARY_SEARCH_JS" ]]; then
        echo -e "${BOLDBLUE}JavaScript Binary Search${ENDCOLOR}"
        echo -e "${BOLDBLUE}====================${ENDCOLOR}"

        if [[ $ITEM_TO_FIND ]]; then
            bun $BINARY_SEARCH_JS $ARRAY_LENGTH $ITEM_TO_FIND
        else
            bun $BINARY_SEARCH_JS $ARRAY_LENGTH
        fi
    else
        echo "$BINARY_SEARCH_JS does not exist."
    fi

}

exec_binary_search_py() {
    if [[ -f "$BINARY_SEARCH_PY" ]]; then
        echo -e "${BOLDYELLOW}Python Binary Search${ENDCOLOR}"
        echo -e "${BOLDYELLOW}====================${ENDCOLOR}"

        if [[ $ITEM_TO_FIND ]]; then
            python3 $BINARY_SEARCH_PY $ARRAY_LENGTH $ITEM_TO_FIND
        else
            python3 $BINARY_SEARCH_PY $ARRAY_LENGTH
        fi
    else
        echo "$BINARY_SEARCH_PY does not exist."
    fi
}

if [[ $ARRAY_LENGTH ]]; then
    exec_binary_search_js
    echo ":::::::::::::::::::::::"
    exec_binary_search_py
else
    echo "No argument found"
fi




